version: '3'

services:
  admin:
    build: .
    image: thealexcode/admin
    restart: always
    ports:
      - '1337:1337'
    volumes:
      - db:/opt/app/.tmp:rw
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
    labels:
      - docker-volume-backup.stop-during-backup=true

  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    env_file: ./backup.env
    volumes:
      - db:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./thealexcode_local_backups:/archive

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ./.tmp/
      o: bind